spring:
  datasource:
    url: jdbc:mysql://47.106.86.98:3306/society?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: society
    password: szdaxh
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  freemarker:
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: catalog/layout/catalog_layout.ftl as layout